@tool
extends Node

## One-shot, step 2 of 2: wires the real imported PNG files (generated by
## generate_flat_textures.gd) into terrain_assets.tres as albedo_texture /
## normal_texture, replacing the in-memory ImageTexture stand-ins that
## Terrain3D refused to use ("not connected to a file").
##
## IMPORTANT: this must run INSIDE the editor process itself (via
## call_method with runtime:false calling fix_textures(), NOT via run_scene
## Play mode) -- Play mode spawns a separate game process with its own
## empty ResourceCache, so anything it does to terrain_assets.tres never
## touches the editor's own live copy (the one Terrain3D's dock actually
## holds and periodically re-serializes to disk, silently undoing fixes
## made from a separate process). Marked @tool so the editor process is
## able to invoke fix_textures() directly.

const ASSETS_PATH := "res://terrain_assets.tres"

## Real 1024x1024 PBR ground materials (ambientCG-style: Color + NormalGL),
## normal maps pre-flattened to 8-bit RGB and albedo alpha channels stripped
## so every texture in the list shares identical size/format -- Terrain3D
## requires this across all texture IDs (see Texture Prep in its docs).
## uv_scale: Terrain3D's flat top-down UV projection distorts more, the
## bigger a single tile is, since a bigger tile means more world-space
## distance gets crammed through the same projection math before the next
## repeat -- a stretch that's a fixed FRACTION of the tile looks like a
## much bigger smear at 1.0 (~1m tiles) than at 2.5 (~0.4m tiles). Ground
## and Rock get the smaller/denser tiling since they're what erosion-carved
## dips and cliff faces actually show; Road stays at 1.0 since it's graded
## flat by _generate_road and doesn't hit this problem.
## detiling_rotation / detiling_shift: Terrain3D's built-in per-tile UV
## randomization (hashed from world position in the shader, see
## addons/terrain_3d/src/shaders/projection.glsl) -- the direct fix for a
## texture repeating identically as far as the eye can see, at zero extra
## art cost. Ground/Rock/Road all get it at full strength (2026-09-16:
## Road used to stay at 0.0, on the reasoning that it should read as one
## consistent, intentionally-graded surface rather than a noisy patchwork
## -- true for the old plain graded-asphalt-style texture, but the
## concrete_rock_path replacement has big, individually-recognizable
## flagstone shapes, and a long narrow road repeats far more of them in a
## visible line than a broad ground area does, so leaving it un-detiled
## made the repeat obvious in exactly the way this setting exists to fix).
## id 0 is named "Ground", not "Grass" (renamed 2026-09-16) -- the source
## texture has always been ambientCG's Ground106 (bare dirt/ground scan),
## never an actual grass texture, so the id was renamed to match what it
## actually shows. A real green grass texture, if/when sourced, should get
## its own id rather than reusing this one.
const TEXTURES_BY_ID := {
	0: {"name": "Ground", "albedo": "res://textures/source/ground_albedo_1k.png", "normal": "res://textures/source/ground_normal_1k.png", "uv_scale": 2.5, "detiling_rotation": 1.0, "detiling_shift": 1.0},
	1: {"name": "Road", "albedo": "res://textures/source/road_albedo_1k.png", "normal": "res://textures/source/road_normal_1k.png", "uv_scale": 1.0, "detiling_rotation": 1.0, "detiling_shift": 1.0},
	## id 2 ("Rock") originally removed -- terrain_gen.gd no longer paints
	## any slope-based rock texture (the generated ridges never got
	## tall/sharp enough to read as cliffs, so the rock blending just
	## looked wrong). Re-added below (2026-09-16) as three new Poly Haven
	## rock varieties (source: D:\Downloads\Godot_v4.7.2-stable_win64.exe\
	## assets\textures\*_1k.blend\textures\, diff jpg + nor_gl exr
	## converted to matching 1024x1024 8-bit RGB, no-alpha PNGs at
	## res://textures/source/ the same way Ground/Road were prepared --
	## the nor_gl exrs were DWAA-compressed, same family as the
	## boulder/rock prop gotcha in CLAUDE.md, but that only bites Godot's
	## own EXR importer; converting to PNG ourselves before it ever
	## reaches Godot sidesteps it entirely). NOT yet painted anywhere in
	## the control map -- see CLAUDE.md / godot_notes/handoff_terrain_textures.md
	## for why slope-based auto-painting is a known dead end here
	## (Terrain3D's enable_projection is off project-wide) and what the
	## untried alternative (painting the control map directly in
	## terrain_gen.gd, like the road already does) looks like. These
	## three are registered as selectable Terrain3DTextureAssets only,
	## for now -- hand-paint with the Terrain3D dock's paint tool, or wire
	## up control-map painting logic separately.
	2: {"name": "RockFace", "albedo": "res://textures/source/rock_face_03_albedo_1k.png", "normal": "res://textures/source/rock_face_03_normal_1k.png", "uv_scale": 2.5, "detiling_rotation": 1.0, "detiling_shift": 1.0},
	3: {"name": "CoastSandRocks", "albedo": "res://textures/source/coast_sand_rocks_02_albedo_1k.png", "normal": "res://textures/source/coast_sand_rocks_02_normal_1k.png", "uv_scale": 2.5, "detiling_rotation": 1.0, "detiling_shift": 1.0},
	4: {"name": "AerialRocks", "albedo": "res://textures/source/aerial_rocks_04_albedo_1k.png", "normal": "res://textures/source/aerial_rocks_04_normal_1k.png", "uv_scale": 2.5, "detiling_rotation": 1.0, "detiling_shift": 1.0},
}

## Strips the id=2 ("Rock") Terrain3DTextureAsset entry from the SAME live
## Terrain3DAssets instance fix_textures() targets (see fix_textures()'s
## own comment for why plain load() -- not CACHE_MODE_IGNORE -- is what
## makes an edit actually stick instead of being silently overwritten by
## the editor's own periodic re-serialize). Terrain3DAssets has no direct
## remove_texture(id) API, so this rebuilds the texture list from
## get_texture_list() with that one entry filtered out and hands the
## result to set_texture_list(). Run via call_method(runtime:false) on the
## EDITOR process, same as fix_textures() -- never via run_scene/Play mode.
func remove_rock_texture() -> String:
	var assets: Terrain3DAssets = load(ASSETS_PATH)
	if assets == null:
		return "ERROR: could not load %s" % ASSETS_PATH

	var kept: Array = []
	var removed := false
	for entry in assets.get_texture_list():
		var tex_asset: Terrain3DTextureAsset = entry
		if tex_asset.get_id() == 2:
			removed = true
			continue
		kept.append(tex_asset)

	if not removed:
		return "id=2 (Rock) not present in %s -- nothing to remove" % ASSETS_PATH

	assets.set_texture_list(kept)
	assets.update_texture_list()
	var err := assets.save(ASSETS_PATH)
	return "removed id=2 (Rock) texture asset; %d texture(s) remain; saved %s (err=%d)" % [kept.size(), ASSETS_PATH, err]

func diag_raw_alpha() -> String:
	# Load the PNG directly as an Image (bypassing the .import/compression
	# pipeline entirely) to check what Godot's own PNG loader sees, before
	# any VRAM-compression format decision happens.
	var img := Image.load_from_file("res://textures/source/road_albedo_1k.png")
	if img == null:
		return "ERROR: could not load image directly"
	return "raw PNG load: format=%s detect_alpha=%s size=%s" % [img.get_format(), img.detect_alpha(), img.get_size()]

func force_reimport() -> String:
	# Overwriting these PNGs on disk (repacking alpha channels, changing
	# import compression settings) doesn't retroactively update textures
	# Godot already has loaded in ResourceCache -- same class of staleness
	# as the terrain_assets.tres saga. EditorFileSystem.reimport_files() is
	# the actual API for forcing a real reimport of already-imported files.
	var paths := [
		"res://textures/source/road_albedo_1k.png",
		"res://textures/source/road_normal_1k.png",
		"res://textures/source/ground_albedo_1k.png",
		"res://textures/source/ground_normal_1k.png",
		"res://textures/source/rock_face_03_albedo_1k.png",
		"res://textures/source/rock_face_03_normal_1k.png",
		"res://textures/source/coast_sand_rocks_02_albedo_1k.png",
		"res://textures/source/coast_sand_rocks_02_normal_1k.png",
		"res://textures/source/aerial_rocks_04_albedo_1k.png",
		"res://textures/source/aerial_rocks_04_normal_1k.png",
	]
	EditorInterface.get_resource_filesystem().reimport_files(PackedStringArray(paths))
	var log_lines: Array[String] = []
	for p in paths:
		var tex: Texture2D = ResourceLoader.load(p, "", ResourceLoader.CACHE_MODE_IGNORE)
		var img: Image = tex.get_image()
		var alpha_state := "n/a"
		if img != null:
			alpha_state = "ALPHA_NONE" if img.detect_alpha() == Image.ALPHA_NONE else "has_alpha"
		log_lines.append("%s -> size=%s format=%s alpha=%s" % [p, tex.get_size(), img.get_format() if img != null else "n/a", alpha_state])
	return "\n".join(log_lines)

func diag_uv_scale() -> String:
	var assets: Terrain3DAssets = load(ASSETS_PATH)
	if assets == null:
		return "ERROR: could not load %s" % ASSETS_PATH
	var log_lines: Array[String] = []
	for entry in assets.get_texture_list():
		var tex_asset: Terrain3DTextureAsset = entry
		log_lines.append("id=%d name=%s uv_scale=%s normal_depth=%s ao_strength=%s roughness=%s" % [tex_asset.get_id(), tex_asset.get_name(), tex_asset.get_uv_scale(), tex_asset.get_normal_depth(), tex_asset.get_ao_strength(), tex_asset.get_roughness()])
	return "\n".join(log_lines)

func fix_textures() -> String:
	# IMPORTANT: plain load() here, deliberately -- this project's Godot editor
	# process keeps ONE canonical Terrain3DAssets instance alive in
	# ResourceCache for as long as the editor is open (Terrain3D's own dock
	# holds a reference to it). A previous version of this script used
	# CACHE_MODE_IGNORE to dodge stale-cache reads, but that means it was
	# mutating a *different*, throwaway copy of the resource -- our fix got
	# saved to disk, but the editor's real in-memory copy (the one Terrain3D
	# actually uses, and periodically re-serializes over our file) never
	# changed, so the old embedded placeholder textures kept coming back.
	# Using plain load() here targets that SAME live instance instead, so
	# the fix actually sticks.
	var assets: Terrain3DAssets = load(ASSETS_PATH)
	if assets == null:
		return "ERROR: could not load %s" % ASSETS_PATH

	var log_lines: Array[String] = []
	# Iterate the desired id->paths mapping (not the existing texture_list),
	# so an id with no Terrain3DTextureAsset yet (e.g. Rock, id=2, added
	# after Ground/Road already existed) gets CREATED here rather than
	# silently skipped -- get_texture(id) returns null for an id that isn't
	# in the list yet, in which case we make a new Terrain3DTextureAsset,
	# set its id, and hand it to assets.set_texture(id, ...), which is what
	# actually inserts it into the live list (assigning into get_texture_list()
	# results directly would not, since that Array is a copy).
	for id in TEXTURES_BY_ID.keys():
		var paths: Dictionary = TEXTURES_BY_ID[id]
		var tex_asset: Terrain3DTextureAsset = assets.get_texture(id)
		var is_new := tex_asset == null
		if is_new:
			tex_asset = Terrain3DTextureAsset.new()
			tex_asset.set_id(id)
		tex_asset.set_name(paths["name"])
		# CACHE_MODE_IGNORE here, deliberately -- these are the LEAF texture
		# files, which we just repacked (alpha channels) and reimported
		# (VRAM compression). A plain load() would hand back whatever was
		# cached from before that repack/reimport. This is safe here (unlike
		# for the Terrain3DAssets container itself, loaded with plain load()
		# above) because we're about to overwrite the live Terrain3DTextureAsset
		# object's property with this fresh value, not relying on it being the
		# "same instance" as anything else.
		var albedo_tex: Texture2D = ResourceLoader.load(paths["albedo"], "", ResourceLoader.CACHE_MODE_IGNORE)
		var normal_tex: Texture2D = ResourceLoader.load(paths["normal"], "", ResourceLoader.CACHE_MODE_IGNORE)
		tex_asset.set_albedo_texture(albedo_tex)
		tex_asset.set_normal_texture(normal_tex)
		# Reset the leftover placeholder tint (green on Ground, yellow on
		# Road, used back when these were flat solid-color stand-ins) to
		# white so it stops multiplying over the real photo textures now
		# assigned above.
		tex_asset.set_albedo_color(Color(1, 1, 1, 1))
		# Terrain3D's uv_scale default (0.1) stretches a texture over ~10m of
		# terrain -- ambientCG-style ground scans like these represent roughly
		# 1-2m of real surface, so 0.1 over-stretches ~5-10x and reads as blur
		# no matter the source resolution. Per-texture value from TEXTURES_BY_ID
		# (Ground/Rock denser than Road) -- see the comment on that dict for
		# why: a smaller tile means any given UV-projection distortion
		# (stretching on cliffs/erosion dips) covers less world-space
		# distance, so it reads as a smaller, less obvious smear even though
		# the underlying projection issue is unchanged.
		tex_asset.set_uv_scale(paths["uv_scale"])
		# See TEXTURES_BY_ID's own comment above for why -- this is the direct,
		# zero-extra-art fix for visible texture repetition.
		tex_asset.set_detiling_rotation(paths.get("detiling_rotation", 0.0))
		tex_asset.set_detiling_shift(paths.get("detiling_shift", 0.0))
		if is_new:
			# This is what actually inserts a brand-new Terrain3DTextureAsset
			# into the live list -- setting properties on a freshly-constructed
			# tex_asset alone does nothing until it's handed to the container.
			assets.set_texture(id, tex_asset)
		log_lines.append("id=%d name=%s %s albedo=%s (%s) normal=%s (%s) albedo_color=white" % [id, tex_asset.get_name(), "(created)" if is_new else "(updated)", paths["albedo"], albedo_tex.get_size(), paths["normal"], normal_tex.get_size()])

	assets.update_texture_list()
	var err := assets.save(ASSETS_PATH)
	log_lines.append("saved %s via Terrain3DAssets.save() (err=%d)" % [ASSETS_PATH, err])
	return "\n".join(log_lines)
